# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target '06-earthquake' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 06-earthquake
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/InAppMessaging'
  pod 'Firebase/Analytics'
  pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git', :branch => 'master'

  target '06-earthquakeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '06-earthquakeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
