

def exec(cmd)
  puts "\e[32m"+cmd+"\e[m"
  puts `#{cmd}`
end

desc 'Send files to raspberrypi.local.'
task :deploy do
  exec("scp m-tsunami-*.py pi@raspberrypi.local:")
end

desc 'Send files to local env.'
task :raspi09 do
  exec("scp m-tsunami-*.py pi@raspi09.local:")
  puts "Next: Set cron along with m-tsunami admin page."
end

task :default => :deploy
